"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../Redux/provider";
import { SessionProvider } from "next-auth/react";
import { authOption } from "./api/auth/[...nextauth]/route";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  { session }: any
) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>
          <Providers>{children}</Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
