"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../Redux/provider";
import AuthProvider from "@/components/AuthProvider";
import MainBlock from "@/components/MainBlock";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  { session }: any
) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>
          <Providers>
            <main
              className="flex h-screen w-screen bg-fill justify-center items-center  text-[2.2rem]
       align-middle text-center m-auto"
            >
              <MainBlock>{children}</MainBlock>
            </main>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
